// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCeXH_wH2JXqABjCXl7nYchlj1xWiBpUw',
    appId: '1:816966798255:web:804127d14a02165c93bd5a',
    messagingSenderId: '816966798255',
    projectId: 'todobackendflutter',
    authDomain: 'todobackendflutter.firebaseapp.com',
    storageBucket: 'todobackendflutter.firebasestorage.app',
    measurementId: 'G-TXFPTEQRBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOH3KDVZrQc4X8_hDxB3zPhq8tnxdCP7c',
    appId: '1:816966798255:android:e029072ae894eacd93bd5a',
    messagingSenderId: '816966798255',
    projectId: 'todobackendflutter',
    storageBucket: 'todobackendflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChZw6kAaluQeGpXIyBjJxqUJD-rFntS6c',
    appId: '1:816966798255:ios:b3c69fe870cc172993bd5a',
    messagingSenderId: '816966798255',
    projectId: 'todobackendflutter',
    storageBucket: 'todobackendflutter.firebasestorage.app',
    iosBundleId: 'com.example.todoBackend',
  );
}
